---

- name: Remove existing cluster "{{ patroni_cluster_name }}" from DCS
  expect:
    command: "patronictl remove {{ patroni_cluster_name }}"
    responses:
      (.*)Please confirm the cluster name to remove: "{{ patroni_cluster_name }}"
      (.*)"Yes I am aware": "Yes I am aware"
  when:
    - inventory_hostname in groups['primary']

...
