---

- name: Ensure "{{ pg_new_datadir }}" exists and is empty for new PostgreSQL
  file:
    path: "{{ pg_new_datadir }}"
    state: "{{ item }}"
    mode: 0700
    group: postgres
    owner: postgres
  loop:
    - absent
    - directory

- name: Get the current encodig and data_checksums settings
  command: psql -tAXc "show {{ item }}"
  changed_when: false
  register: pg_settings
  loop:
    - server_encoding
    - lc_collate
    - lc_ctype
    - lc_messages
    - lc_monetary
    - lc_numeric
    - lc_time
    - data_checksums

# Use initdb, if the PostgreSQL configuration is located in the data directory.
- name: Initialize a new PostgreSQL data directory
  command: >
    {{ pg_new_bindir }}/initdb
    --pgdata={{ pg_new_datadir }}
    --encoding={{ pg_settings.results[0].stdout }}
    --lc-collate={{ pg_settings.results[1].stdout }}
    --lc-ctype={{ pg_settings.results[2].stdout }}
    --lc-messages={{ pg_settings.results[3].stdout }}
    --lc-monetary={{ pg_settings.results[4].stdout }}
    --lc-numeric={{ pg_settings.results[5].stdout }}
    --lc-time={{ pg_settings.results[6].stdout }}
    {% if pg_settings.results[7].stdout == 'on' %}
    --data-checksums
    {% endif %}
  when:
    - pg_new_confdir == pg_new_datadir

# Use pg_createcluster, if the PostgreSQL configuration is not located in the data directory.
# Note: Patroni failure is possible if the default postgresql config files are missing in the /etc/postgresql/...
# Note: pre-execute the pg_dropcluster command to be able to re-init
- name: Initialize a new PostgreSQL data directory with default postgresql config files
  command: >
    /usr/bin/pg_dropcluster --stop {{ pg_new_version }} {{ postgresql_cluster_name }} ;
    /usr/bin/pg_createcluster {{ pg_new_version }} {{ postgresql_cluster_name }}
    -d {{ pg_new_datadir }}
    -e {{ pg_settings.results[0].stdout }}
    --start-conf manual
    --
      --lc-collate={{ pg_settings.results[1].stdout }}
      --lc-ctype={{ pg_settings.results[2].stdout }}
      --lc-messages={{ pg_settings.results[3].stdout }}
      --lc-monetary={{ pg_settings.results[4].stdout }}
      --lc-numeric={{ pg_settings.results[5].stdout }}
      --lc-time={{ pg_settings.results[6].stdout }}
      {% if pg_settings.results[7].stdout == 'on' %}
      --data-checksums
      {% endif %}
  when:
    - ansible_os_family == "Debian"
    - pg_new_confdir != pg_new_datadir

...
