---

- name: Ensure the current data directory is the new data directory
  command: psql -tAXc "show data_directory"
  changed_when: false
  register: pg_current_datadir

# RedHat based
- name: Delete the old PostgreSQL data directory
  file:
    path: "{{ pg_old_datadir }}"
    state: absent
  when:
    - pg_new_datadir == pg_current_datadir.stdout | trim
    - ansible_os_family == "RedHat"

# Debian based (use pg_dropcluster)
- name: Delete the old PostgreSQL data directory (perform pg_dropcluster)
  command: >
    /usr/bin/pg_dropcluster {{ pg_old_version }} {{ postgresql_cluster_name }}
  failed_when: false
  when:
    - pg_new_datadir == pg_current_datadir.stdout | trim
    - ansible_os_family == "Debian"

# RedHat based
- name: Remove old PostgreSQL packages
  become: true
  become_user: root
  package:
    name: "{{ item }}"
    state: absent
  loop: "{{ postgresql_packages | regex_replace(postgresql_version, pg_old_version) }}"
  register: package_remove
  until: package_remove is success
  delay: 5
  retries: 3
  ignore_errors: true
  when:
    - item is search(pg_old_version)
    - pg_old_packages_remove | bool
    - ansible_os_family == "RedHat"

# Debian based (use purge option)
- name: Remove old PostgreSQL packages
  become: true
  become_user: root
  apt:
    name: "{{ item }}"
    state: absent
    purge: true
  loop: "{{ postgresql_packages | regex_replace(postgresql_version, pg_old_version) }}"
  register: apt_remove
  until: apt_remove is success
  delay: 5
  retries: 3
  ignore_errors: true
  when:
    - item is search(pg_old_version)
    - pg_old_packages_remove | bool
    - ansible_os_family == "Debian"

- name: Check the Patroni cluster state
  run_once: true
  become: true
  become_user: postgres
  command: "patronictl -c {{ patroni_config_file }} list"
  register: patronictl_result
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
  when: inventory_hostname in groups['primary']

- name: Check the current PostgreSQL version
  run_once: true
  command: psql -tAXc "select current_setting('server_version')"
  register: postgres_version
  changed_when: false
  when: inventory_hostname in groups['primary']

# Return the pg_hba.conf file to its original state (if it has been changed)
- block:
    - name: Remove temporary local access rule for the "postgres" user
      blockinfile:
        path: "{{ pg_new_confdir }}/pg_hba.conf"
        marker: "# {mark} ANSIBLE TEMPORARY pg_upgrade RULE"
        state: absent

    - name: Update the PostgreSQL configuration
      command: "{{ pg_new_bindir }}/pg_ctl reload -D {{ pg_new_datadir }}"
  when:
    - socket_access_result.stderr is defined
    - "'no pg_hba.conf entry' in socket_access_result.stderr"

# finish (info)
- name: List the Patroni cluster members
  run_once: true
  debug:
    msg: "{{ patronictl_result.stdout_lines }}"
  when: patronictl_result.stdout_lines is defined

- name: Upgrade completed
  run_once: true
  debug:
    msg:
      - "PostgreSQL upgrade completed."
      - "Current version: {{ postgres_version.stdout }}"
  when: postgres_version.stdout is defined

...
